import 'package:faker/faker.dart';
import 'package:gymaster/core/database/database_helper.dart';
import 'package:gymaster/core/database/models/models.dart';
import 'package:gymaster/core/generated/assets.gen.dart';
import 'package:gymaster/shared/utils/uuid_generator.dart';

class RoutineDataSeeder {
  final IdGenerator idGenerator;

  RoutineDataSeeder({required this.idGenerator});

  Future<List<RoutineDbModel>> generateFakeRutinas() async {
    final db = await DatabaseHelper.instance.database;
    var faker = Faker();
    List<RoutineDbModel> rutinas = [];
    List<String> imagenDireccion = [
      Assets.icons.otros.biceps.path,
      Assets.icons.otros.bicicletaDeSpinning.path,
      Assets.icons.otros.estirar.path,
      Assets.icons.otros.gymEquipamiento.path,
      Assets.icons.otros.pantorrillas.path,
      Assets.icons.otros.pierna.path,
      Assets.icons.otros.pesas.path,
      Assets.icons.otros.pesas1.path,
      Assets.icons.otros.manosConOpesas.path,
      Assets.icons.otros.biceps.path,
      Assets.icons.otros.bicicletaDeSpinning.path,
      Assets.icons.otros.estirar.path,
      Assets.icons.otros.gymEquipamiento.path,
      Assets.icons.otros.pantorrillas.path,
      Assets.icons.otros.pierna.path,
      Assets.icons.otros.pesas.path,
      Assets.icons.otros.pesas1.path,
      Assets.icons.otros.manosConOpesas.path,
      Assets.icons.otros.biceps.path,
      Assets.icons.otros.bicicletaDeSpinning.path,
      Assets.icons.otros.estirar.path,
      Assets.icons.otros.gymEquipamiento.path,
      Assets.icons.otros.pantorrillas.path,
      Assets.icons.otros.pierna.path,
      Assets.icons.otros.pesas.path,
      Assets.icons.otros.pesas1.path,
      Assets.icons.otros.manosConOpesas.path,
      Assets.icons.otros.biceps.path,
      Assets.icons.otros.bicicletaDeSpinning.path,
      Assets.icons.otros.estirar.path,
      Assets.icons.otros.gymEquipamiento.path,
      Assets.icons.otros.pantorrillas.path,
      Assets.icons.otros.pierna.path,
      Assets.icons.otros.pesas.path,
      Assets.icons.otros.pesas1.path,
      Assets.icons.otros.manosConOpesas.path,
      Assets.icons.otros.biceps.path,
      Assets.icons.otros.bicicletaDeSpinning.path,
      Assets.icons.otros.estirar.path,
      Assets.icons.otros.gymEquipamiento.path,
      Assets.icons.otros.pantorrillas.path,
      Assets.icons.otros.pesas.path,
    ];
    List<String> nombresRutinas = [
      'Rutina de Fuerza',
      'Rutina de Cardio',
      'Rutina de Resistencia',
      'Rutina de Flexibilidad',
      'Rutina de HIIT',
      'Rutina de Yoga',
      'Rutina de Pilates',
      'Rutina de CrossFit',
      'Rutina de Ciclismo',
      'Rutina de Natación',
      'Rutina de Boxeo',
      'Rutina de Kickboxing',
      'Rutina de Artes Marciales',
      'Rutina de Calistenia',
      'Rutina de Gimnasia',
      'Rutina de Atletismo',
      'Rutina de Escalada',
      'Rutina de Senderismo',
      'Rutina de Esquí',
      'Rutina de Snowboard',
      'Rutina de Surf',
      'Rutina de Remo',
      'Rutina de Triatlón',
      'Rutina de Maratón',
      'Rutina de Media Maratón',
      'Rutina de Sprint',
      'Rutina de Velocidad',
      'Rutina de Potencia',
      'Rutina de Agilidad',
      'Rutina de Equilibrio',
      'Rutina de Coordinación',
      'Rutina de Movilidad',
      'Rutina de Recuperación',
      'Rutina de Rehabilitación',
      'Rutina de Prevención de Lesiones',
      'Rutina de Pérdida de Peso',
      'Rutina de Ganancia de Masa',
      'Rutina de Definición',
      'Rutina de Tono Muscular',
      'Rutina de Endurance',
      'Rutina de Core',
      'Rutina de Glúteos',
    ];
    List<int> colores = [
      0xFFF48FB1,
      0xFFB39DDB,
      0xFF90CAF9,
      0xFF80DEEA,
      0xFFA5D6A7,
      0xFFE6EE9C,
      0xFFFFE082,
      0xFFFFAB91,
      0xFFB0BEC5,
      0xFFBCAAA4,
      0xFFFFCC80,
      0xFFFFF59D,
      0xFFC5E1A5,
      0xFF80CBC4,
      0xFF81D4FA,
      0xFFEF9A9A,
      0xFF9FA8DA,
      0xFFCE93D8,
      0xFFD1C4E9,
      0xFFBBDEFB,
      0xFFB2EBF2,
      0xFFAED581,
      0xFFFFF176,
      0xFFFF8A65,
      0xFFCFD8DC,
      0xFFD7CCC8,
      0xFFFFE0B2,
      0xFFFFF9C4,
      0xFFE6EE9C,
      0xFFDCEDC8,
      0xFFB3E5FC,
      0xFFB2DFDB,
      0xFFB3E5FC,
      0xFFFFCDD2,
      0xFFC5CAE9,
      0xFFE1BEE7,
      0xFFD7CCC8,
      0xFFB0BEC5,
      0xFFBCAAA4,
      0xFFFFCC80,
      0xFFFFF59D,
      0xFFC5E1A5,
      0xFF80CBC4,
      0xFF81D4FA,
      0xFFEF9A9A,
      0xFF9FA8DA,
      0xFFCE93D8,
      0xFFD1C4E9,
      0xFFBBDEFB,
      0xFFB2EBF2,
    ];

    List<DateTime> fechasCreacion = [
      DateTime(2024, 11, 5),
      DateTime(2024, 11, 10),
      DateTime(2024, 11, 15),
      DateTime(2024, 11, 20),
      DateTime(2024, 11, 25),
      DateTime(2024, 11, 30),
      DateTime(2024, 12, 5),
      DateTime(2024, 12, 10),
      DateTime(2024, 12, 15),
      DateTime(2024, 12, 20),
      DateTime(2024, 12, 25),
      DateTime(2024, 12, 30),
      DateTime(2025, 1, 4),
      DateTime(2025, 1, 9),
      DateTime(2025, 1, 14),
      DateTime(2025, 1, 19),
      DateTime(2025, 1, 24),
      DateTime(2025, 1, 29),
      DateTime(2024, 11, 6),
      DateTime(2024, 11, 11),
      DateTime(2024, 11, 16),
      DateTime(2024, 11, 21),
      DateTime(2024, 11, 26),
      DateTime(2024, 12, 1),
      DateTime(2024, 12, 6),
      DateTime(2024, 12, 11),
      DateTime(2024, 12, 16),
      DateTime(2024, 12, 21),
      DateTime(2024, 12, 26),
      DateTime(2024, 12, 31),
      DateTime(2025, 1, 5),
      DateTime(2025, 1, 10),
      DateTime(2025, 1, 15),
      DateTime(2025, 1, 20),
      DateTime(2025, 1, 25),
      DateTime(2024, 11, 7),
      DateTime(2024, 11, 12),
      DateTime(2024, 11, 17),
      DateTime(2024, 11, 22),
      DateTime(2024, 11, 27),
      DateTime(2024, 12, 2),
      DateTime(2024, 12, 7),
      DateTime(2024, 12, 12),
      DateTime(2024, 12, 17),
      DateTime(2024, 12, 22),
      DateTime(2024, 12, 27),
      DateTime(2025, 1, 1),
      DateTime(2025, 1, 6),
      DateTime(2025, 1, 11),
      DateTime(2025, 1, 16),
      DateTime(2025, 1, 21),
      DateTime(2025, 1, 26),
    ];

    for (int i = 0; i < nombresRutinas.length; i++) {
      DateTime fechaCreacion = fechasCreacion[i];
      // DateTime fechaRealizacion = fechaCreacion.add(
      //   Duration(days: faker.randomGenerator.integer(30, min: 1)),
      // );

      await db.insert(
        RoutineDbModel.table,
        RoutineDbModel(
          id: idGenerator.generateId(),
          name: nombresRutinas[i],
          description: faker.lorem.sentence(),
          createdAt: fechaCreacion.toIso8601String(),
          color: colores[i],
          imagePath: imagenDireccion[i],
          userId: '1',
        ).toJson(),
      );
    }

    return rutinas;
  }
}
