name: gymaster
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_gen_runner: ^5.8.0
  flutter_svg: ^2.0.14
  logger: ^2.5.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  equatable: ^2.0.5
  fpdart: ^1.1.1
  animate_do: ^3.3.4
  circular_countdown_timer: ^0.2.4
  go_router: ^14.6.2
  flutter_localization: ^0.2.2
  sqflite_common_ffi: ^2.3.4+3
  shared_preferences: ^2.3.5
  faker: ^2.0.0
  iconsax_plus: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9

# El paquete "flutter_lints" que se incluye a continuación contiene un conjunto de lints recomendados para
# fomentar buenas prácticas de codificación. El conjunto de lints que proporciona el paquete se
# activa en el archivo `analysis_options.yaml` ubicado en la raíz de su
# paquete. Consulte ese archivo para obtener información sobre cómo desactivar reglas de lint
# específicas y activar otras adicionales.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/iconsax/
    - assets/imagenes/otros/
    - assets/imagenes/fondos/
    - assets/imagenes/musculos/
    - assets/imagenes/musculos/abdomen/
    - assets/imagenes/musculos/antebrazo/
    - assets/imagenes/musculos/biceps/
    - assets/imagenes/musculos/cuadriceps/
    - assets/imagenes/musculos/espalda/
    - assets/imagenes/musculos/espalda_baja/
    - assets/imagenes/musculos/femorales/
    - assets/imagenes/musculos/gluteo/
    - assets/imagenes/musculos/hombro/
    - assets/imagenes/musculos/pantorrilla/
    - assets/imagenes/musculos/pecho/
    - assets/imagenes/musculos/trapecio/
    - assets/imagenes/musculos/triceps/
    - assets/imagenes/musculos/general/
  fonts:
    - family: ZonaPro
      fonts:
         - asset: fonts/zona-pro/ZonaPro-Regular.ttf
         - asset: fonts/zona-pro/ZonaPro-RegularItalic.ttf
         - asset: fonts/zona-pro/ZonaPro-Thin.ttf
         - asset: fonts/zona-pro/ZonaPro-ThinItalic.ttf
         - asset: fonts/zona-pro/ZonaPro-Bold.ttf
         - asset: fonts/zona-pro/ZonaPro-BoldItalic.ttf
           #weight: 100
           #style: normal

flutter_gen:
  output: lib/core/generated/
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true